spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/state-monitoring
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

queue:
  name: httprequest
